version: '3.9'

services:
  db:
    restart: always
    image: mysql:latest
    # container_name: mysql-container # コンテナ名を指定するとき
    # platform: linux/x86_64 # Mac用
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: root # パスワードを指定するとき
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  db:
